CREATE TABLE influence_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    workout_id INTEGER
        REFERENCES influence_workouts(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES influence_users(id) ON DELETE CASCADE NOT NULL
);
